LuxoriaSoft/Luxoria

- Luxoria.App/Luxoria.App/App.xaml.cs
- Luxoria.App/Luxoria.App/Dialogs/OpenCollectionDialog.cs
- Luxoria.App/Luxoria.Core.Tests/ModuleServiceTests.cs
- Luxoria.App/Luxoria.Core.Tests/StartupTests.cs
- Luxoria.App/Luxoria.Core/Logics/Startup.cs
- Luxoria.App/Luxoria.Modules.Tests/BusTests.cs
- Luxoria.App/Luxoria.Modules.Tests/ModuleContextTests.cs
- Luxoria.App/Luxoria.Modules/EventBus.cs
- Luxoria.App/Luxoria.Modules/Interfaces/IEvent.cs
- Luxoria.App/Luxoria.Modules/Interfaces/IEventBus.cs
- Luxoria.App/Luxoria.Modules/Interfaces/IModuleContext.cs
- Luxoria.App/Luxoria.Modules/Models/Events/CollectionUpdatedEvent.cs
- Luxoria.App/Luxoria.Modules/Models/Events/ImageUpdatedEvent.cs
- Luxoria.App/Luxoria.Modules/Models/Events/LogEvent.cs
- Luxoria.App/Luxoria.Modules/Models/Events/OpenCollectionEvent.cs
- Luxoria.App/Luxoria.Modules/Models/Events/TextInputEvent.cs
- Luxoria.App/Luxoria.Modules/ModuleContext.cs
- Luxoria.App/Luxoria.SDK.Tests/LoggerServiceTests.cs
- Luxoria.App/Luxoria.SDK/Interfaces/IFileHasherService.cs
- Luxoria.App/Luxoria.SDK/Interfaces/ILogTarget.cs
- Luxoria.App/Luxoria.SDK/Interfaces/ILoggerService.cs
- Luxoria.App/Luxoria.SDK/Models/LogLevel.cs
- Luxoria.App/Luxoria.SDK/Services/LoggerService.cs
- Luxoria.App/Luxoria.SDK/Services/Targets/DebugLogTarget.cs
- Luxoria.App/Luxoria.SDK/Services/Targets/FileLogTarget.cs
1. Improve Logger service to handle logging target as a file or on the output
2. Fix all warnings coming from Unit Tests
> feat: Some improvements on Architecture and Core functions

- .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
- .github/pull_request_template.md
- CODE_OF_CONDUCT.md
---
---
---
---
Fixes #77  
Closes #77
---
---
---
---
> feat: Add open source docs/templates

- buildsystem.py
**Title:** `[LDA] - (Core) Refactor Build System`  
---
This PR brings a new buildsystem developed in python.
This build system will clear the caches by deleting the obj and bin folders of each part of the project.
Then, it will compile Luxoria.App, then Each part of Luxoria.App and finally each modules described in the modules list
---
---
---
Fixes #80
Closes #80 
---
This build has been tested using python 3.12 and python 3.13
---
---
---
> fix: Refactor General build system

- Luxoria.App/Luxoria.App/EventHandlers/CollectionUpdatedHandler.cs
- Luxoria.App/Luxoria.Modules.Tests/ImageDataTests.cs
- Luxoria.App/Luxoria.Modules.Tests/ModuleContextTests.cs
- Luxoria.App/Luxoria.Modules/Luxoria.Modules.csproj
- Luxoria.App/Luxoria.Modules/Models/ImageData.cs
- Modules/LuxImport/LuxImport/LuxImport.cs
- Modules/LuxImport/LuxImport/LuxImport.csproj
- Modules/LuxImport/LuxImport/Services/ImportService.cs
- Modules/LuxImport/LuxImport/Utils/ImageDataHelper.cs
**Title:** `[LDA] - (Mods) Add improvements in LuxImport module`  
---
This PR brings some changes in **LuxImport** solution and include SkiaSharp lib inside **Luxoria.Modules**
1. Import & Include SkiaSharp inside Luxoria.Modules
2. Change **ReadOnlyMemory**<byte> pixelsData to **SKBitmap** bitmap
3. Change the importation method to import an SKBitmap instead of a list of bytes (improve performance)
4. Add filters to indexation method to ignore files which are not related to any format of photo (png, jpeg, ...)
5. Integrate new version of unit tests for testing this model
---
---
---
Fixes #82,#66
---
This fix has been tested using 'fix/mods/luximport' branch.
---
> fix: Add improvements in LuxImport v1.0.1

- LICENSE.md
**Title:** `[LXX] - (Repo) Add license Apache 2.0`  
**Assignees:**  @QuentinCraft @epi-noahg @Lucas25000 
---
This PR adds a license to Luxoria Project.
---
---
---
---
This PRs adds only a license.
No test needs to be retested
---
---
---
> feat: Add license `Apache 2.0`

- README.md
**Title:** `[LXX] - (Docs) Fix License link in README`  
---
This PR adds a small change on the README file that now includes a License section.
---
---
---
---
---
---
---
> fix: Update LICENSE link in README to point to LICENSE.md

- Luxoria.App/Luxoria.App/MainWindow.xaml.cs
- Luxoria.App/Luxoria.SDK/Luxoria.SDK.csproj
- Luxoria.App/Luxoria.SDK/Services/LoggerService.cs
**Title:** `[LDA] - (Core) Add Sentry`  
**Assignees:**  @Lucas25000 
---
Add Sentry to project in order to handle all kind of errors
---
---
---
Fixes #55
---
Test ok
---
---
---
> feat: Add sentry to project in LoggerService

- .github/workflows/luxapi-build.yml
**Title:** `[LWA] - (CICD) Add workflow for building LuxAPI solution`  
---
This PR brings :
1. Creation of a workflow
2. Adding the following tasks inside the workflow :
3. Fetch the project
4. Restore the nuget packages for LuxAPI
5. Build LuxAPI in Release configuration
6. Publish LuxAPI in Release configuration
FYI : SDK used for this workflow : dotnet@8.0.405
---
---
---
Fixes #99 
---
Tests OK ! Using this action : https://github.com/LuxoriaSoft/Luxoria/actions/runs/12843429292
---
---
---
> feat: Add GitHub Actions workflow for LuxAPI build process

- .github/workflows/lda-build.yml
- .github/workflows/release.yml
**Title:** `[LDA] - (CI/CD) Improve building workflow`  
---
This PR brings :
1. An LDA-build workflow which is trigger when a PR is open, re-open or merged
2. Change the artifact retention from 1d to 1w
---
---
---
---
Tests OK !
---
---
---
> feat: Add build and release workflows for Luxoria Desktop App

- Modules/LuxFilter/LuxFilter.Algorithms/Algorithms/ImageQuality/SharpnessAlgo.cs
- Modules/LuxFilter/LuxFilter.Algorithms/Utils/ImageProcessing.cs
**Title:** `[LDA] - (Filter) fix: Simplify some functions in LuxFilter`  
---
This PR brings some refactor on LuxFilter solution
---
---
---
---
Test OK ! Using previous output
---
---
---
> fix: Simplify some functions in LuxFilter

- .github/workflows/build.yml
**Title:** `[LDA] - (CICD) Fix launch test command on build.yml workflow`  
---
This PR fixes the .NET test run command on build workflow
---
---
---
---
Tests OK ! (Using Unit Tests)
---
---
---
> fix: Fix .NET launch test running command

- Modules/LuxFilter/LuxFilter/LuxFilter.cs
- Modules/LuxImport/LuxImport.Tests/CustomGuidConverterTests.cs
- Modules/LuxImport/LuxImport.Tests/CustomLuxCfgResolverTests.cs
- Modules/LuxImport/LuxImport.Tests/ImageDataHelperTests.cs
- Modules/LuxImport/LuxImport.Tests/LuxConfigRepositoryTests.cs
- Modules/LuxImport/LuxImport.Tests/LuxImportServiceTests.cs
- Modules/LuxImport/LuxImport.Tests/ManifestRepositoryTests.cs
- Modules/LuxImport/LuxImport/Services/ImportService.cs
**Title:** `[LDA] - (Tests) Add tests cases on LuxXYZ Modules`  
---
This PR brings :
1. Addition of test cases on LuxImport (Services, Repositories & Core functions)
---
---
---
---
Tests OK ! Using xUnit 
---
---
---
> feat: Add tests cases on LuxXYZ Modules

- docs/desktop/README.md
- docs/desktop/luxstd/LUXFILTER.md
- docs/desktop/luxstd/LUXIMPORT.md
- docs/desktop/luxstd/README.md
**Title:** `[LDA] - (Docs) docs: Add docs about LuxSTD (Luxoria Standard Modules)`  
---
This PR brings some docs about LuxSTD (Luxoria Standard Modules)
---
---
---
---
Docs ONLY
---
---
---
> docs: Add docs about LuxSTD (Luxoria Standard Modules) [skip ci]

- Luxoria.App/Luxoria.App/App.xaml.cs
- Modules/LuxImport/LuxImport/LuxImport.cs
- Modules/LuxImport/LuxImport/Services/ImportService.cs
**Title:** `[LDA] - (Mods) Delete simulated delays in import process`  
---
This PR deletes the simulated delays in LuxImport for improving perf.
---
---
---
---
Tests OK ! Using xUnit / Github Workflow
---
---
---
> refactor: Delete simulated delays in import process

- Luxoria.App/Luxoria.App/EventHandlers/CollectionUpdatedHandler.cs
- Luxoria.App/Luxoria.Modules/Models/FileExtension.cs
- Luxoria.App/Luxoria.Modules/Models/ImageData.cs
- Modules/LuxImport/LuxImport/LuxImport.csproj
- Modules/LuxImport/LuxImport/Services/ImportService.cs
- Modules/LuxImport/LuxImport/Utils/ImageDataHelper.cs
**Title:** `[LDA] - (Import) Include EXIF Data / Operate on RAW/ARW / Auto Rotate SKBitmap`  
---
This PR brings :
1. Now the ImageDataHelper can operates on RAW / ARW formats
2. Including EXIF data on ImageData thanks to `MetadataExtractor`
3. Automatic Rotation of the SKBitmap at its initialization
---
---
---
Fixes #124 , #125 , #126 
---
Tests OK (Using xUnit) !
---
---
---
> feat: Include EXIF Data / Operate on RAW/ARW / Auto Rotate SKBitmap

- .github/workflows/release.yml
- Luxoria.App/Luxoria.App/Logics/Startup.cs
- Luxoria.App/Luxoria.App/Luxoria.App.csproj
- Luxoria.App/Luxoria.App/Luxoria.App.csproj.user
- Luxoria.App/Luxoria.App/MainWindow.xaml.cs
**Title:** `[LDA] - (Core) fix: Change Luxoria.App build system from packaged to unpackaged version`  
---
This PR updates the build system of Luxoria.App, transitioning from a packaged deployment model to an unpackaged version. The changes ensure compatibility with the new build workflow and improve flexibility in deployment.
1. Modified the MSBuild publish process to support unpackaged deployment.
2. Adjusted GitHub Actions workflow to correctly handle build artifacts.
3. Ensured output structure aligns with the new unpackaged deployment model.
---
---
---
---
Provide a brief description of how you tested your changes. Include details about the environment and test cases …
> fix: Change Luxoria.App build system from packaged to unpackaged version

- .github/workflows/dependabot.yml
**Title:** `[LXX] - (CI) Add dependabot to CI workflows`  
---
This PR brings Dependabot automatic updater
---
---
---
Fixes #146
---
---
---
---
> feat: Add Dependabot to CI workflows

- .github/workflows/dependabot.yml
**Title:** `[LXX] - (CI) feat: Update Dependabot target-branch to Develop`  
---
This PR changes the target branch of Dependabot to Develop
---
---
---
---
---
---
---
> feat: Update Dependabot target-branch to Develop

- .github/workflows/dependabot.yml
- CHANGELOG.md
**Title:** `[LXX] - (Merge) Develop to Main`  
---
This PR merges develop to main
---
---
---
---
---
---
---
> merge: Merge develop to main

- Luxoria.App/Luxoria.App/Services/ModuleService.cs
- Luxoria.App/Luxoria.Modules.Tests/ImageDataTests.cs
- Luxoria.App/Luxoria.Modules/Models/Events/CollectionUpdatedEvent.cs
- Luxoria.App/Luxoria.Modules/Models/Events/FilterCatalogEvent.cs
- Luxoria.App/Luxoria.Modules/Models/Events/LogEvent.cs
- Luxoria.App/Luxoria.Modules/Models/Events/README.md
- Luxoria.App/Luxoria.Modules/Models/Events/RequestWindowHandleEvent.cs
- Luxoria.App/Luxoria.Modules/Models/Events/TextInputEvent.cs
- Luxoria.App/Luxoria.Modules/Models/ImageData.cs
- Modules/LuxFilter/LuxFilter.Algorithms/LuxFilter.Algorithms.csproj
- Modules/LuxFilter/LuxFilter/LuxFilter.cs
- Modules/LuxFilter/LuxFilter/LuxFilter.csproj
- Modules/LuxFilter/LuxFilter/LuxFilter.csproj.user
- Modules/LuxFilter/LuxFilter/Services/FilterService.cs
- Modules/LuxFilter/LuxFilter/Services/PipelineService.cs
- Modules/LuxFilter/LuxFilter/Views/FilterView.xaml
- Modules/LuxFilter/LuxFilter/Views/FilterView.xaml.cs
- Modules/LuxFilter/LuxFilter/Views/MainFilterView.xaml
- Modules/LuxFilter/LuxFilter/Views/MainFilterView.xaml.cs
- Modules/LuxFilter/LuxFilter/Views/StatusView.xaml
- Modules/LuxFilter/LuxFilter/Views/StatusView.xaml.cs
**Title:** `[LDA] - (Filter) feat: Add UI interface for LuxFilter's module`  
---
This PRs brings an Graphical User Interface for LuxFilter module.
---
---
---
Fixes #144 
---
Has been tested using xUnit
---
https://github.com/user-attachments/assets/c7b8bb42-856b-4154-a8f4-cfbea6123a76
---
---
> feat: Add UI for LuxFilter's module

- Modules/LuxExport/LuxExport/Components/ExportProgressWindow.xaml.cs
**Title:** `[LDA] - (GUI) feat: Integration of LMGUI/LuxEditor @ 1.0.1`  
@epi-noahg 
---
Modify commentaries in a file for better understanding
---
---
> feat: Integration of LMGUI/LuxEditor @ 1.0.1

- Modules/LuxFilter/LuxFilter.Algorithms/Algorithms/ColorVisualAesthetics/CLIPModel/clip_image_encoder.onnx
---
---
---
---
---
---
---
---
> fix: Disable LFS storage

- Modules/LuxFilter/.gitattributes
---
---
---
---
---
---
---
---
> fix: Remove LFS filter for ONNX files

- CHANGELOG.md
- Modules/LuxFilter/.gitattributes
---
---
---
---
---
---
---
---
> merge: Develop to Main

- LuxStudio/LuxAPI/LuxAPI/Controllers/AuthController.cs
**Title:** `[LWA] - (Core) fix: WhoAmI method returns User method without sensitive informations`  
---
This PR fixes the WhoAmI (AuthController) method by returning an `User` model with masking sensitive informations.
---
---
---
Fixes #207 
---
Depl : OK !
xUnit : OK !
---
---
---
> fix: WhoAmI method returns User method without sensitive informations

- LuxStudio/LuxAPI/LuxAPI/Controllers/AuthController.cs
- LuxStudio/LuxAPI/LuxAPI/Controllers/SSOController.cs
**Title:** `[LWA] - (Core) hotfix: Fix generation of JWT Token on SSOController`  
---
This PR temporarily fixes the JWT Token generation on SSOController
@Lucas25000 It should be very useful to have a JWTService or JWTManager to create on the same way each token.
@Lucas25000 Will U do it ? 
---
---
---
Fixes #207 
---
Depl : OK !
---
---
---
> hotfix: Fix generation of JWT Token on SSOController

- LuxStudio/LuxAPI/LuxAPI/Controllers/AuthController.cs
- LuxStudio/LuxAPI/LuxAPI/Controllers/SSOController.cs
- LuxStudio/LuxAPI/LuxAPI/Program.cs
- LuxStudio/LuxAPI/LuxAPI/Services/Interfaces/IJWTService.cs
- LuxStudio/LuxAPI/LuxAPI/Services/JWTService.cs
**Title:** `[LWA] - (Core) refactor: Creation of JWT Service to manage JWT Creation`  
---
This PR refactors the way to create the JWT Token by creating a class attached to the `IJwtService` singleton, to create a unified way of JWT management.
---
---
---
Fixes #207
---
Depl : OK !
---
---
---
> refactor: Creation of JWT Service to manage JWT Creation

- .github/workflows/release-artifacts.yml
---
---
---
---
---
---
---
---
> fix: Rename job identifiers

- .github/workflows/marketplace-upload.yml
- tools/luxmktplacemgr/.gitignore
- tools/luxmktplacemgr/pyproject.toml
- tools/luxmktplacemgr/src/luxmktplacemgr/main.py
- tools/luxmktplacemgr/src/uploadmgr/main.py
**Title:** `[LXX] - (CICD) feat: Integrate LuxMarketPlace Manager`  
---
---
---
---
---
---
---
---
> feat: Integrate LuxMarketPlace Manager

- .github/workflows/marketplace-upload.yml
---
---
---
---
---
---
---
---
> fix: Checkout code before executing script

- tools/luxmktplacemgr/pyproject.toml
---
---
---
---
---
---
---
---
> fix: Change python version from >=3.13 to >=3.11 for marketplacemgr

- .github/workflows/marketplace-upload.yml
- tools/luxmktplacemgr/src/uploadmgr/main.py
---
---
---
---
---
---
---
---
> fix: Inject GH_TOKEN as secret using Github secrets

- Modules/LuxEditor/LuxEditor/Components/Editor.xaml.cs
- Modules/LuxEditor/LuxEditor/Logic/LayerManager.cs
- Modules/LuxEditor/LuxEditor/Models/Layer.cs
**Title:** `[LDA] - (Editor) feat: Integration of LuxEditor @2.0.1`  
**Assignees:** @epi-noahg  
---
This PR correct the layer management in the tree view.
---
---
---
Fixes #145   
---
Tested on Windows with different image formats, including RAW, JPEG, and PNG.
---
---
---
> feat: Integration of LuxEditor @2.0.1

- Modules/LuxImport/luxmod.json
**Title:** `[LDA] - (Marketplace) fix: Add brochure field to luxmod.json`  
---
This PR brings the brochure feature for Lux Marketplace.
---
---
---
---
---
---
---
> fix: Add brochure field to luxmod.json

- .github/workflows/build-upload-lda.yml
**Title:** `[LXX] - (CICD) fix: Clean up artifact zip [x64, x86, arm64]`  
---
This PR formats the artifact zip at the end of of the PUBLISH folder, default root was /bin/ARCH/CONFIG/FRAMEWORK/PUBLISH
---
---
---
---
Using Deployment pipeline used : https://github.com/LuxoriaSoft/Luxoria/actions/runs/15738449718
---
---
---
> fix: Clean up artifact zip [x64, x86, arm64]

- Luxoria.App/Luxoria.App/Components/MainMenuBarComponent.xaml.cs
- Luxoria.App/Luxoria.App/Views/MarketplaceView.xaml.cs
**Title:** `[LDA] - (Marketplace) Add async fetches for Luxoria's releases + Add animations when a module has been installed`  
---
This PR adds an async fetches for Luxoria's releases + Adds animations when a module has been installed
---
---
---
Fixes #288, #265 
---
Using xUnit
---
---
---
> fix: Add async fetches for releases & Animation when a module has been installed.

- Modules/LuxEditor/LuxEditor/Components/Editor.xaml
- Modules/LuxEditor/LuxEditor/Components/Editor.xaml.cs
- Modules/LuxEditor/LuxEditor/Components/PhotoViewer.xaml
- Modules/LuxEditor/LuxEditor/Components/PhotoViewer.xaml.cs
- Modules/LuxEditor/LuxEditor/EditorUI/Controls/CropController.cs
- Modules/LuxEditor/LuxEditor/EditorUI/Controls/ToolSelectorBar.cs
- Modules/LuxEditor/LuxEditor/Logic/CropProcessor.cs
- Modules/LuxEditor/LuxEditor/LuxEditor.cs
- Modules/LuxEditor/LuxEditor/Models/EditableImage.cs
**Title:** `[LDA] - (Editor) feat: Integration of LuxEditor @2.0.4`  
**Assignees:**  @epi-noahg 
---
This pr add the crop tool.
---
---
---
Fixes #145 
---
Tested on Windows with different image formats, including RAW, JPEG, and PNG.
---
---
---
> feat: Integration of LuxEditor @2.0.4

- Modules/LuxExport/LuxExport/Components/Export.xaml
- Modules/LuxExport/LuxExport/Components/Export.xaml.cs
- Modules/LuxExport/LuxExport/Components/ExportProgressWindow.xaml.cs
- Modules/LuxExport/LuxExport/Logic/ExportViewModel.cs
- Modules/LuxExport/LuxExport/Logic/WatermarkApplier.cs
- Modules/LuxExport/LuxExport/Logic/WatermarkService.cs
- Modules/LuxExport/LuxExport/Logic/WatermarkSettings.cs
- Modules/LuxExport/LuxExport/LuxExport.cs
**Title:** `[LDA] - (LuxExport) add: Watermarks`  
**Assignees:**  @epi-noahg 
---
This pr add the watermark system.
---
---
---
Fixes #13 
---
---
---
---
> Feat: Integration of Luxexport-> Add watermarks

- Modules/LuxStudio/luxmod.json
**Title:** `[LDA] - (Studio) fix: Fix/luxstudio/luxmod `  
---
This PR adds a luxmod.json for LuxStudio
---
---
---
---
---
---
---
> fix: Fix/luxstudio/luxmod

- CHANGELOG.md
- Modules/LuxStudio/luxmod.json
**Title:** `[LXX] - (Merge) develop to main`  
---
This PR merges develop to main
---
---
---
---
---
---
---
> fix: Develop to Main

- Modules/LuxEditor/LuxEditor/LuxEditor.cs
- Modules/LuxExport/LuxExport/LuxExport.cs
- Modules/LuxStudio/LuxStudio/LuxStudio.cs
**Title:** `[LDA] - (Modules) feat: Fix names of modules in navigation bar`  
**Assignees:**  @epi-noahg 
---
Rename modules in navigation bar (e.g. LuxEditor -> Editor) 
---
---
---
Fixes #390
> feat: Fix names of modules in navigation bar

- .github/workflows/release-artifacts.yml
**Title:** `[LXX] - (CICD) fix: Upload exe as artifacts unzipped (version)`  
---
This PR fixes the upload workflow for attaching exe(s) as artifacts unzipped (version)
---
---
---
Fixes #389 
---
---
---
---
> fix: Upload exe as artifacts unzipped (version)

- .github/workflows/release-artifacts.yml
**Title:** `[LXX] - (CICD) fix: Upload exe before zipping the remaining part`  
---
This PR fixes the upload exe before zipping the remaining part
---
---
---
---
---
---
---
> fix: Upload exe before zipping the remaining part

- .github/workflows/release-artifacts.yml
**Title:** `[LXX] - (CICD) fix: Include all LuxoriaSetup before zipping the remaining file`  
---
This PR includes all LuxoriaSetup before zipping the remaining file
---
---
---
---
---
---
---
> fix: Include all LuxoriaSetup before zipping the remaining file

- .github/workflows/release-artifacts.yml
**Title:** `[LXX] - (CICD) fix: Specify artifact list instead of *.exe`  
---
This PR specifies artifact list instead of *.exe
---
---
---
---
---
---
---
> fix: Specify artifact list instead of *.exe

- .github/workflows/release-artifacts.yml
**Title:** `[LXX] - (CICD) fix: Necessary env. variable known as GITHUB_TOKEN for retrieving and attaching artifacts`  
---
fix: Necessary env. variable known as GITHUB_TOKEN for retrieving and attaching artifacts
---
---
---
---
---
---
---
> fix: Necessary env. variable known as GITHUB_TOKEN for retrieving and attaching artifacts

- .github/workflows/release-artifacts.yml
**Title:** `[LXX] - (CICD) fix: Enable Flatten when downloads artifacts`  
---
This fixes enable Flatten when downloads artifacts
---
---
---
---
---
---
---
> fix: Enable Flatten when downloads artifacts

- tools/luxmktplacemgr/src/uploadmgr/main.py
…upload_dirs param list
**Title:** `[LDA] - (Import) fix: Upload to marketplace python script by specifying branch_src`  
---
This PR fixes the following failed workflow : https://github.com/LuxoriaSoft/Luxoria/actions/runs/17459513243
---
---
---
---
---
---
---
> fix: Upload to marketplace python script by specifying branch_src

- Modules/LuxExport/LuxExport/Logic/ExportPresetService.cs
- Modules/LuxExport/LuxExport/Logic/ExportViewModel.cs
**Title:** `[LDA] - (Filter) fix: Specify TypeInfoResolver (fixing crashes on x86)`  
---
This PR fixes a permanent crash on x86 (only on Release mode)
---
---
---
---
---
---
---
> fix: Specify TypeInfoResolver (fixing crashes on x86)

- Modules/LuxEditor/LuxEditor/EditorUI/Controls/LayersDetailsPanel.cs
**Title:** `[LDA] - (Editor) fix: Sliders not sliding smoothly in Layers`  
**Assignees:**  @epi-noahg 
---
fixing sliders in Layers
---
---
---
Fixes #409
> fix: Sliders not sliding smoothly in Layers

- Modules/LuxStudio/LuxStudio/LuxStudio.cs
**Title:** `[LDA] - (Studio) fix: Remove debug messages`  
---
fix: Remove debug messages
---
---
---
---
---
---
---
> fix: Remove debug messages

- .circleci/config.yml
- LuxStudio/depl/overlays/saturn/configmap-luxdb-init.yaml
- LuxStudio/depl/overlays/saturn/ingress.yaml
- LuxStudio/depl/overlays/saturn/kustomization.yaml
- LuxStudio/depl/overlays/saturn/luxapi-secrets.sh
- LuxStudio/depl/overlays/saturn/namespace.yaml
- LuxStudio/depl/overlays/saturn/patch-deployment-luxapi.yaml
- LuxStudio/depl/overlays/saturn/patch-deployment-luxstudio.yaml
- LuxStudio/depl/saturn/deployment.yaml
- LuxStudio/depl/saturn/ingress.yaml
- LuxStudio/depl/saturn/service.yaml
**Title:** `[LXX] - (CICD) feat: Bring Saturn Deployment In`  
---
This PR brings the Saturn Environment Deployment inside the CircleCI deployment workflow
---
---
- [w] New feature (non-breaking change that adds functionality)
---
---
---
---
---
> feat: Bring Saturn Deployment In

- CHANGELOG.md
- LuxStudio/LuxAPI/LuxAPI/Controllers/AdminController.cs
- LuxStudio/LuxAPI/LuxAPI/Controllers/AuthController.cs
- LuxStudio/LuxAPI/LuxAPI/Controllers/CollectionController.cs
- LuxStudio/LuxAPI/LuxAPI/Program.cs
- LuxStudio/LuxAPI/LuxAPI/Services/AdminOnlyFilter.cs
- LuxStudio/LuxAPI/LuxAPI/Services/EmailService.cs
- LuxStudio/LuxAPI/LuxAPI/appsettings.Development.json
- LuxStudio/LuxAPI/LuxAPI/appsettings.json
- LuxStudio/portalv2/src/app/(app)/collections/[id]/page.tsx
- LuxStudio/portalv2/src/app/(app)/forbidden/page.tsx
- LuxStudio/portalv2/src/app/admin/users/page.tsx
- LuxStudio/portalv2/src/services/admin.services.ts
- LuxStudio/portalv2/src/services/api.ts
**Title:** `[LWA] - (LuxAPI) fix: Bring a lot of security measures into LuxAPI`  
**Assignees:**  @Lucas25000 
---
This PR integrates a huge number of security fixes and patches into LuxAPI.
Changes already built and integrated into the latest docker image : https://hub.docker.com/layers/luxoria/luxapi/20250913.777/images/sha256-80db1f0f828b65b283191bbb1f85fa97b0b89b93d86a74267f1f0e1f2e935cb1
---
---
---
No issue attached
---
using xUnit
---
---
---
> fix: Bring a lot of security measures into LuxAPI
